name: CI Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened]

jobs:
    lint:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  cache: "yarn"
                  node-version: ">=18.12.0"
            - name: Install dependencies
              run: yarn install
            - name: Check Lint
              run: yarn checkLint
              continue-on-error: true
            - name: Fix Lint Issues
              run: yarn lintFix
              if: ${{ failure() }}

    build:
        needs: [lint]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  cache: "yarn"
                  node-version: ">=18.12.0"
            - name: Install dependencies
              run: yarn install
            - name: Build
              run: yarn build
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist

    test:
        needs: [build]
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  cache: "yarn"
                  node-version: ">=18.12.0"
            - name: Install dependencies
              run: yarn install
            - uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist
            - name: Test
              run: yarn test
